"""
Admin panel constants and configuration.
"""

# Authentication
ADMIN_MAX_LOGIN_ATTEMPTS = 3
ADMIN_LOCKOUT_DURATION_SECONDS = 300  # 5 minutes
ADMIN_PASSWORD_MIN_LENGTH = 8

# Encryption
ENCRYPTION_ALGORITHM = "AES-256-CBC"
ENCRYPTION_KEY_LENGTH = 32  # 256 bits
ENCRYPTION_SALT_LENGTH = 32
ENCRYPTION_IV_LENGTH = 16

# Image Upload
MAX_IMAGE_SIZE_MB = 10
MAX_IMAGE_SIZE_BYTES = MAX_IMAGE_SIZE_MB * 1024 * 1024
ALLOWED_IMAGE_EXTENSIONS = ["jpg", "jpeg", "png"]
IMAGE_RESIZE_WIDTH = 1280
IMAGE_RESIZE_HEIGHT = 960

# Question Management
MAX_HINTS_PER_QUESTION = 10
MAX_QUESTION_DESCRIPTION_LENGTH = 500
